&AddText&
Type:23,False,False,False

ElementsCount:0
END

&functions&
Type:15,False,False,False
ElementsCount:2
Type:16,False,False,False
BuildResetEPDஐFalse
ElementsCount:2
Type:17,False,False,False
ElementsCount:1
Type:8,False,False,False
act:CreateVariableWithNoini
unitEPDஐ35
ElementsCount:0
END
END
Type:18,False,False,False
ElementsCount:2
Type:21,False,False,False
/*ToolTipஐ*/ஐTrue
ElementsCount:1
Type:22,False,False,False
ElementsCount:2
Type:21,False,False,False
KoreanஐKoreanஐFalse
ElementsCount:1
Type:22,False,False,False
ElementsCount:3
Type:8,False,False,False
act:RawCode
구조오프셋EPD
ElementsCount:0
END
Type:8,False,False,False
act:CreateVariableWithNoini
unitEPDஐ35
ElementsCount:0
END
Type:8,False,False,False
act:RawCode
의 생산 대기열을 초기화합니다.
ElementsCount:0
END
END
END
Type:21,False,False,False
EnglishஐEnglishஐFalse
ElementsCount:1
Type:22,False,False,False
ElementsCount:0
END
END
END
END
Type:8,False,False,False
act:RawCode
unitEPD += 0x098 / 4;
const oldcp = getcurpl();
setcurpl(unitEPD);
DoActions(list(
SetDeaths(CurrentPlayer, SetTo, 0xE400E4, 0),
SetMemory(0x6509B0, Add, 1),
SetDeaths(CurrentPlayer, SetTo, 0xE400E4, 0),
SetMemory(0x6509B0, Add, 1),
SetDeathsX(CurrentPlayer, SetTo, 228, 0, 0xFFFF),
SetMemory(0x6509B0, Add, 1),
SetDeathsX(CurrentPlayer, SetTo, 0x20000, 0, 0xFF0000),
));
setcurpl(oldcp);
ElementsCount:0
END
END
END
Type:16,False,False,False
BuildCheckEPDஐFalse
ElementsCount:2
Type:17,False,False,False
ElementsCount:2
Type:8,False,False,False
act:CreateVariableWithNoini
unitEPDஐ35
ElementsCount:0
END
Type:8,False,False,False
act:CreateVariableWithNoini
Unitஐ3
ElementsCount:0
END
END
Type:18,False,False,False
ElementsCount:3
Type:21,False,False,False
/*ToolTipஐ*/ஐTrue
ElementsCount:1
Type:22,False,False,False
ElementsCount:2
Type:21,False,False,False
KoreanஐKoreanஐFalse
ElementsCount:1
Type:22,False,False,False
ElementsCount:5
Type:8,False,False,False
act:RawCode
구조오프셋EPD
ElementsCount:0
END
Type:8,False,False,False
act:CreateVariableWithNoini
unitEPDஐ35
ElementsCount:0
END
Type:8,False,False,False
act:RawCode
이
ElementsCount:0
END
Type:8,False,False,False
act:CreateVariableWithNoini
Unitஐ3
ElementsCount:0
END
Type:8,False,False,False
act:RawCode
를 생산중인지 확인합니다.
ElementsCount:0
END
END
END
Type:21,False,False,False
EnglishஐEnglishஐFalse
ElementsCount:1
Type:22,False,False,False
ElementsCount:0
END
END
END
END
Type:1,False,True,False
ElementsCount:2
Type:3,False,True,False
Or
ElementsCount:5
Type:7,False,False,False
con:CUnitDataEPD
unitEPDஐ70ஐ0ஐUnit
ElementsCount:0
END
Type:7,False,False,False
con:CUnitDataEPD
unitEPDஐ71ஐ0ஐUnit
ElementsCount:0
END
Type:7,False,False,False
con:CUnitDataEPD
unitEPDஐ72ஐ0ஐUnit
ElementsCount:0
END
Type:7,False,False,False
con:CUnitDataEPD
unitEPDஐ73ஐ0ஐUnit
ElementsCount:0
END
Type:7,False,False,False
con:CUnitDataEPD
unitEPDஐ74ஐ0ஐUnit
ElementsCount:0
END
END
Type:5,False,True,False
ElementsCount:1
Type:8,False,False,False
act:RawCode
return True
ElementsCount:0
END
END
END
Type:8,False,False,False
act:RawCode
return False
ElementsCount:0
END
END
END
END

&GlobalVar&
Type:0,False,False,False
ElementsCount:1
Type:8,False,False,False
act:CreatePlayerVariable
Heroஐ0
ElementsCount:0
END
END

&RawTriggers&
Type:25,False,False,False
ElementsCount:0
END

&onPluginStart&
Type:0,False,False,False
ElementsCount:0
END

&beforeTriggerExec&
Type:0,False,False,False
ElementsCount:1
Type:10,False,False,False
PlayerLoopஐ1,1,1,1,1,1,1,1,0,0,0,0ஐ10
ElementsCount:1
Type:14,False,False,False
ElementsCount:5
Type:1,False,False,False
ElementsCount:2
Type:3,False,False,False
And
ElementsCount:1
Type:7,False,False,False
con:Deaths
13ஐ0ஐ1ஐ205
ElementsCount:0
END
END
Type:5,False,False,False
ElementsCount:2
Type:28,False,False,False
dwread_epd(EPD(0x58A364 + 48 * 205 + 4 * getcurpl()))
ElementsCount:2
Type:29,False,False,False
1ஐTrue
ElementsCount:2
Type:8,False,False,False
act:SetNextUnitEPD
Hero[getcurpl()]
ElementsCount:0
END
Type:28,False,False,False
dwread_epd(EPD(0x58A364 + 48 * 121 + 4 * getcurpl()))
ElementsCount:15
Type:29,False,False,False
1ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ20ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
2ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ53ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
3ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ77ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
4ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ10ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
5ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ54ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
6ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ78ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
7ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ1ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
8ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ103ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
9ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ64ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
10ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ17ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
11ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ39ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
12ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ79ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
13ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ95ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
14ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ61ஐ4ஐ13
ElementsCount:0
END
END
Type:29,False,False,False
15ஐTrue
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ76ஐ4ஐ13
ElementsCount:0
END
END
END
END
Type:29,False,False,False
2ஐTrue
ElementsCount:0
END
END
Type:8,False,False,False
act:SetDeaths
13ஐ0ஐ0ஐ205
ElementsCount:0
END
END
END
Type:1,False,False,False
ElementsCount:2
Type:3,False,False,False
And
ElementsCount:1
Type:19,False,False,False
BuildCheckEPDஐHero[getcurpl()]ஐ70
ElementsCount:0
END
END
Type:5,False,False,False
ElementsCount:1
Type:19,False,False,False
BuildResetEPDஐHero[getcurpl()]
ElementsCount:0
END
END
END
Type:1,False,False,False
ElementsCount:2
Type:3,False,False,False
And
ElementsCount:1
Type:19,False,False,False
BuildCheckEPDஐHero[getcurpl()]ஐ72
ElementsCount:0
END
END
Type:5,False,False,False
ElementsCount:1
Type:19,False,False,False
BuildResetEPDஐHero[getcurpl()]
ElementsCount:0
END
END
END
Type:1,False,False,False
ElementsCount:2
Type:3,False,False,False
And
ElementsCount:1
Type:19,False,False,False
BuildCheckEPDஐHero[getcurpl()]ஐ71
ElementsCount:0
END
END
Type:5,False,False,False
ElementsCount:1
Type:19,False,False,False
BuildResetEPDஐHero[getcurpl()]
ElementsCount:0
END
END
END
Type:1,False,False,False
ElementsCount:2
Type:3,False,False,False
And
ElementsCount:2
Type:7,False,False,False
con:CUnitDataEPD
Hero[getcurpl()]ஐ31ஐ0ஐ141
ElementsCount:0
END
Type:7,False,False,False
con:CUnitDataEPD
Hero[getcurpl()]ஐ42ஐ0ஐHero[getcurpl()]
ElementsCount:0
END
END
Type:5,False,False,False
ElementsCount:1
Type:8,False,False,False
act:CreateUnit
1ஐ9ஐ1ஐ13
ElementsCount:0
END
END
END
END
END
END

&afterTriggerExec&
Type:0,False,False,False
ElementsCount:0
END

